### PR TITLE
DDFHER-123 - Update `dynamic_entity_reference` to "3.2.0"

### PR DESCRIPTION
**Pull request by kasperbirch1**
#### Link to issue
https://reload.atlassian.net/browse/DDFHER-123

#### Description
This update includes patch `3405253`, which renames the feild to `Dynamic entity reference`, making it more distinguishable from core entity reference field types that use the `Reference` label.

### CODE REVIEW

**Comment by kasperg** [comment]
@kasperbirch1 Does it make sense to add a Cypress test for this?

**Comment by kasperbirch1** [comment]
> @kasperbirch1 What do you think about adding a Cypress test for this?

Yes, I can do that, but is it okay to add it in the [paragraphs test](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1706)? The paragraph card_grid_manual uses dynamic_entity_reference.

**Comment by kasperg** [comment]
:+1: Let's do that.

**Review by kasperg — APPROVED** [review]

**Comment by kasperg** [comment]
:+1: This is good to merge.

**Pull request merged**
