### PR TITLE
Change opac to next + Remove .test from publizon service

### PR DESCRIPTION
**Pull request by kasperbirch1**
#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-416
https://reload.atlassian.net/browse/DSC-34

#### This PR change following:
- Change profile on `fbi-api` from 'opac' to 'next'
- Change `publizon` service to production

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

### CODE REVIEW

**Review by kasperg — APPROVED** [review]
:+1: LGTM

**Review by kasperg — CHANGES_REQUESTED** [review]
There are other places that reference the `opac` part of the url e.g. the Wiremock mappings.

This is probably also why all the tests that use the mappings fail.

Please correct this.

**Review by cableman — APPROVED** [review]
Note: have you test that http://pubhub-openplatform.dbc.dk actually works. It has returned 500 on almost all request for a very long time now...

**Comment by kasperbirch1** [comment]
> 

I tested it in 'dpl-react' and it works there.
image

**Pull request merged**
